# Generated by Django 6.0.5 on 2026-05-28 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='embed_disabled',
            field=models.BooleanField(default=False),
        ),
    ]
