# Generated by Django 6.0.5 on 2026-06-08 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_video_embed_disabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='recommended',
            field=models.BooleanField(default=False),
        ),
    ]
