# Generated by Django 6.0.5 on 2026-06-15 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_video_recommended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='curator_note',
            field=models.TextField(),
        ),
    ]
